#!/bin/sh


if false; then
	# Wait for asterisk to init Dect stack
	until pidof asterisk >/dev/null; do
		echo "Waiting for bootup to finish..."
		sleep 1
	done
	
	until logread | grep -q "dectshim open device"; do
		echo "Waiting for bootup to finish..."
		sleep 1
	done
	
	killall -q dectdbgd
	sleep 2
	
	# Enable radio
	dect -x 1
	sleep 1
	
	# Don't let asterisk disturb us
	killall -q -STOP asterisk
	
	# Enable test mode
	cat "/etc/dect/dect_testmode.dat" >"/dev/dectdbg"
	sleep 1
	
	
	if logread | grep -q "dect: Test Mode Enabled"; then
		echo "Dect test mode enabled"
	
		# Flash box led
		ubus call led.dect set '{ "state": "alert" }'
	
		# Dectmanager should not do anything from now on
		killall -q -STOP dectmngr
	
		exit 0
	else
		echo "Failed enabling dect test"
		exit 1
	fi


else
	if [ "$1" == "enable" ]; then
		dectcalib -e
	elif [ "$1" == "disable" ]; then
		dectcalib -d
	else
		printf "Usage: dect_testmode [ enable ] [ disable ]\n"
		exit 1
	fi
	
	
	# kill asteriskt and dectmngr before proxy since they bind to it
	/etc/init.d/asterisk stop 2>/dev/null
	/etc/init.d/dect stop 2>/dev/null
	killall -q dectproxy dectmngr
	rmmod dect
	sleep 1
	
	#load kernel module
	insmod /lib/modules/3.4.11-rt19/extra/dect.ko
	sleep 1
	
	#start dectproxy & mngr
	/etc/init.d/dect start 2>/dev/null
	
	#initialize stack
	sleep 2
	dect -i
fi


