#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org
START=99
STOP=10

DEST=
DEFAULT=$DEST/etc/default/asterisk
OPTIONS=""


start() {
	# avoid fp timing problem
	echo 1 > /proc/sys/kernel/printk_with_interrupts_enabled
	
	# init dect
	sleep 15
	/root/dectmngr -i
	/root/dectmngr -d
}

stop() {
        killall -9 dectmngr
}

restart() {
	echo "restart dect"
}
